const nodemailer = require('nodemailer');

exports.sendInvoiceEmail = async (emailAddress, invoice) => {
  // Use real Gmail SMTP transport
  let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  // send mail with defined transport object
  let info = await transporter.sendMail({
    from: `"VendorBridge ERP" <${process.env.SMTP_USER}>`, // sender address
    to: emailAddress, // list of receivers
    subject: `VendorBridge Invoice Dispatched - ${invoice.invoice_number}`, // Subject line
    text: `Hello,

Please find attached the official invoice generated for your Procurement Order.
  - Invoice Number: ${invoice.invoice_number}
  - Purchase Order: ${invoice.po_number}
  - Vendor Company: ${invoice.company_name}
  - Project/RFQ:   ${invoice.rfq_title}
  - Grand Total:   $${parseFloat(invoice.total_amount).toFixed(2)} USD (GST Included)

This email was successfully generated by the VendorBridge ERP system.`, 
    html: `
    <div style="font-family: 'Inter', Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
      
      <!-- Header -->
      <div style="background-color: #2563eb; color: #ffffff; padding: 30px 20px; text-align: center;">
        <h1 style="margin: 0; font-size: 24px; font-weight: 700; letter-spacing: 1px;">VENDORBRIDGE</h1>
        <p style="margin: 5px 0 0; font-size: 14px; opacity: 0.9;">Enterprise Procurement Operations</p>
      </div>
      
      <!-- Body -->
      <div style="padding: 30px 20px; background-color: #ffffff;">
        <h2 style="margin-top: 0; color: #1f2937; font-size: 20px;">Invoice Generated Successfully</h2>
        <p style="color: #4b5563; font-size: 15px; line-height: 1.6;">Hello,</p>
        <p style="color: #4b5563; font-size: 15px; line-height: 1.6;">Please find the details for your officially generated invoice below. This transaction has been recorded in our ERP system.</p>
        
        <!-- Details Box -->
        <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 20px; margin: 25px 0;">
          
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; color: #64748b; font-size: 13px; font-weight: 600; text-transform: uppercase; width: 40%;">Invoice Number</td>
              <td style="padding: 8px 0; color: #0f172a; font-size: 14px; font-weight: 600; text-align: right;">${invoice.invoice_number}</td>
            </tr>
            <tr style="border-top: 1px solid #e2e8f0;">
              <td style="padding: 8px 0; color: #64748b; font-size: 13px; font-weight: 600; text-transform: uppercase;">PO Reference</td>
              <td style="padding: 8px 0; color: #0f172a; font-size: 14px; text-align: right;">${invoice.po_number}</td>
            </tr>
            <tr style="border-top: 1px solid #e2e8f0;">
              <td style="padding: 8px 0; color: #64748b; font-size: 13px; font-weight: 600; text-transform: uppercase;">Vendor Company</td>
              <td style="padding: 8px 0; color: #0f172a; font-size: 14px; text-align: right;">${invoice.company_name}</td>
            </tr>
            <tr style="border-top: 1px solid #e2e8f0;">
              <td style="padding: 8px 0; color: #64748b; font-size: 13px; font-weight: 600; text-transform: uppercase;">Project / RFQ</td>
              <td style="padding: 8px 0; color: #0f172a; font-size: 14px; text-align: right;">${invoice.rfq_title}</td>
            </tr>
          </table>
          
          <div style="margin-top: 15px; padding-top: 15px; border-top: 2px dashed #cbd5e1; text-align: right;">
            <p style="margin: 0; color: #64748b; font-size: 13px; font-weight: 600; text-transform: uppercase;">Grand Total (inc. GST)</p>
            <p style="margin: 5px 0 0; color: #2563eb; font-size: 24px; font-weight: 700;">$${parseFloat(invoice.total_amount).toLocaleString('en-US', {minimumFractionDigits: 2, maximumFractionDigits: 2})} USD</p>
          </div>
          
        </div>
        
        <p style="color: #64748b; font-size: 14px; text-align: center; margin-top: 30px;">
          You can view or download the full PDF version of this invoice directly from your VendorBridge dashboard.
        </p>
      </div>
      
      <!-- Footer -->
      <div style="background-color: #f1f5f9; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0;">
        <p style="margin: 0; color: #94a3b8; font-size: 12px;">This is an automated system message generated by VendorBridge ERP.</p>
        <p style="margin: 5px 0 0; color: #94a3b8; font-size: 12px;">Please do not reply directly to this email.</p>
      </div>
      
    </div>
    `
  });

  console.log("Message sent: %s", info.messageId);
  return true;
};
